src/shortenerTools/UrlRedirect/UrlRedirect.cs
src/shortenerTools/proxies.json

Allow anonimous

---

src/shortenerTools/Domain/StorageTableHelper.cs

It's case sensitive to it needed to be uppercase
Issue #16

Set the RowKey to KEY

---

README.md
deployment/azureDeploy.json
deployment/azureDeploy.params.json
how-it-works.md
src/shortenerTools/.vscode/settings.json
src/shortenerTools/UrlRedirect/UrlRedirect.cs
src/shortenerTools/settings.json

The default Url is now in the setting.json file, and can be specified at deployment time.
AZURL#1 
#1

Add Default URL in setting and at deployment

---

.vscode/settings.json
README.md
azFunctions-deployment.md
how-it-works.md
post-deployment-configuration.md
src/adminTools/README.md
src/adminTools/adminBlazorWebsite/README.md
src/adminTools/postman/README.md

Adding more documentation about how it works
closing issue #32, #34

Adding more documentation about how it works

---

deployment/azureDeploy.json
src/adminTools/adminBlazorWebsite/deployment/adminBlazorWebsite-deployAzure.json
src/adminTools/adminBlazorWebsite/deployment/adminBlazorWebsite-deployAzure.params.json

Quickfix adding new setting in deployment

Quickfix adding new setting in deployment

---

deployment/azureDeploy.json
src/adminTools/adminBlazorWebsite/deployment/adminBlazorWebsite-deployAzure.json
src/adminTools/adminBlazorWebsite/deployment/adminBlazorWebsite-deployAzure.params.json
src/adminTools/adminBlazorWebsite/src/Data/UrlShortenerService.cs
src/adminTools/adminBlazorWebsite/src/appsettings.json

Optimization Refact #53

---

src/shortenerTools/Domain/StorageTableHelper.cs

Kudos to the video with @shanselman where I noticed this.

Fix spelling in comment

---

AzUrlShortener.sln
src/adminTools/adminBlazorWebsite/src/appsettings.json
src/shortenerTools/shortenerTools.csproj

For those who like to work with full Visual Studio instead of VS Code.
Also updated NuGet packages and made function project target netcoreapp3.1

Added VS solution file

---

.vscode/launch.json
.vscode/settings.json
azFunctions-deployment.md
src/adminTools/adminBlazorWebsite/src/Data/ShortUrlEntity.cs
src/adminTools/adminBlazorWebsite/src/Data/UrlShortenerService.cs
src/adminTools/adminBlazorWebsite/src/Pages/Urls.razor
src/shortenerTools/.vscode/settings.json
src/shortenerTools/Domain/ShortResponse.cs
src/shortenerTools/Domain/ShortUrlEntity.cs
src/shortenerTools/Domain/StorageTableHelper.cs
src/shortenerTools/UrlArchive/UrlArchive.cs
src/shortenerTools/UrlShortener/UrlShortener.cs

* Fix spelling in comment
* Fix the spelling error "Bellow" to "Below"
* IsArchived bit flag introduced. Archive button added to the frontend that hides the url but leaves the statistics in Azure table storage
Co-authored-by: Frank Boucher <2404846+FBoucher@users.noreply.github.com>
Co-authored-by: Bernard Vander Beken <bernard@jawn.net>
Co-authored-by: IronManion <36028632+IronManion@users.noreply.github.com>
Co-authored-by: Anth <ak785@icloud.com>
Co-authored-by: Anth <anthony.kernan@gmail.com>

Feature/soft delete (#2)

---

.gitignore
.vscode/settings.json
src/adminTools/adminBlazorWebsite/src/Data/ShortUrlEntity.cs
src/shortenerTools/.vscode/settings.json

add ... at the end

---

src/adminTools/adminBlazorWebsite/src/Data/ShortUrlEntity.cs

Blazor Admin - Long URL cut of h in https #97
Beginners question - if I change this code, How can I verify this code version on my tenant?

#97 - Blazor Admin - Long URL cut of h in https

---

.all-contributorsrc
README.md
src/adminTools/adminBlazorWebsite/src/Data/ShortUrlEntity.cs
src/adminTools/adminBlazorWebsite/src/Data/ShortUrlRequest.cs
src/adminTools/adminBlazorWebsite/src/Pages/Urls.razor
src/adminTools/adminBlazorWebsite/src/Shared/Modal.razor
src/shortenerTools/UrlShortener/UrlShortener.cs
src/shortenerTools/UrlUpdate/UrlUpdate.cs

Force of the habit.. .I merged the PR into dev...

Bringing lastest PR into vNext

---

README.md

Changed branch target from 'master' to 'main' to fix issue #133

Updated Azure Deploy Badge URI

---

src/adminTools/postman/README.md

Was setting things up and came upon this broken link

Fix broken link to post deployment configuration

---

src/adminTools/PowerShell/README.md
src/adminTools/PowerShell/src/BulkImportUrls.csv
src/adminTools/PowerShell/src/PowerShell_BulkImportUrls.ps1

Feature request (idea): Allow bulk shortener generation #135

Bulk importer

---

README.md

move dependabot And hard-coded main-v1

---

src/shortenerTools/Domain/Utility.cs
src/shortenerTools/Properties/PublishProfiles/patientcommsshortenertools2fxfh - Zip Deploy.pubxml
src/shortenerTools/Properties/ServiceDependencies/patientcommsshortenertools2fxfh - Zip Deploy/profile.arm.json

Shuffle character set so that generated vanity codes aren't obviously sequential.
Enforce a minimum length for vanity codes.

Shortenvanitychanges

---

deployment/azureDeploy.json

Found a small Typo in Json file

improvement in json file

---

doc/azFunctions-deployment.md

Retarget Deploy to Azure button to main

---

Initialize.cs
domain/StorageTableHelper.cs

https://github.com/FBoucher/AzUrlShortener/issues/441

441 Missing URL tables

---

.all-contributorsrc

fix contributor bot

---

.github/workflows/azure-static-web-apps-kind-ocean-0b86fe110.yml
src/Cloud5mins.ShortenerTools.Core/Cloud5mins.ShortenerTools.Core.csproj
src/Cloud5mins.ShortenerTools.Functions/Cloud5mins.ShortenerTools.Functions.csproj
src/Cloud5mins.ShortenerTools.Functions/Program.cs
src/Cloud5mins.ShortenerTools.TinyBlazorAdmin/Cloud5mins.ShortenerTools.TinyBlazorAdmin.csproj

Update target framework versions and package references

Upgraded to .NET 8 

---

src/Cloud5mins.ShortenerTools.Api/ShortenerEnpoints.cs
src/Cloud5mins.ShortenerTools.Core/Cloud5mins.ShortenerTools.Core.csproj
src/Cloud5mins.ShortenerTools.Core/Domain/ImportUrlData.cs
src/Cloud5mins.ShortenerTools.Core/Service/AzStrorageTablesService.cs
src/Cloud5mins.ShortenerTools.Core/Service/IAzStrorageTablesService.cs
src/Cloud5mins.ShortenerTools.Core/Service/UrlServices.cs
src/Cloud5mins.ShortenerTools.Core/Service/Utility.cs
src/Cloud5mins.ShortenerTools.FunctionsLight/Cloud5mins.ShortenerTools.FunctionsLight.csproj
src/Cloud5mins.ShortenerTools.TinyBlazorAdmin/Cloud5mins.ShortenerTools.TinyBlazorAdmin.csproj
src/Cloud5mins.ShortenerTools.TinyBlazorAdmin/Components/Pages/Settings.razor
src/Cloud5mins.ShortenerTools.TinyBlazorAdmin/Components/Shared/ImportData.razor
src/Cloud5mins.ShortenerTools.TinyBlazorAdmin/Components/Shared/ScheduleComponent.razor
src/Cloud5mins.ShortenerTools.TinyBlazorAdmin/UrlManagerClient.cs

That adding the feature #553 Make it easier to import data from previous version

Import data From UI

---

.github/copilot-instructions.md
src/Core/Messages/UrlClickStatsRequest.cs
src/Core/Service/AzStrorageTablesService.cs
src/Core/Service/IAzStrorageTablesService.cs
src/Core/Service/UrlServices.cs
src/TinyBlazorAdmin/Components/Pages/Statistics.razor

Add Start and End date filters on Statistic page
fixing #551

Add date filters on Statistic page
